# Base image
FROM nginx:latest

# Install dependencies
RUN apt-get update -qq && apt-get -y install apache2-utils

ADD ./nginx.conf /etc/nginx/nginx.conf
 
EXPOSE 80
 
# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]