version: '2'

services: 
  db:
    image: postgres:9.6.6
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
  nginx:
    image: nginx: latest
    build:
      context: ./nginx
      dockerfile: "./nginx/Dockerfile"
    volumes:
      - ./logs:var/log
    ports:
      - "80:80"
    depends_on: 
      - web
  web:
    build:
      context: ./hello_app
      dockerfile: "./hello_app/Dockerfile"
    environment:
      PORT: "3000"
      RAILS_ENV: production
    depends_on:
      - db